version: 0.2

phases:
  install:
    runtime-versions:
      java: 21
    commands:
      - echo Installing dependencies...

  pre_build:
    commands:
      - echo Pre-build phase
      - mvn clean

  build:
    commands:
      - echo Building, Testing and packaging the application...
      - mvn package -DskipTests

  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - target/*.jar
